### ISSUE TITLE
Crooked server retention

### ISSUE THREAD

**Issue by Vladik01-11** [RinatNamazov/SampX#1]
Your server saving is not working correctly, I deleted several servers and when I re-logged in, I found them again. I checked on all releases, exactly the same.

https://github.com/RinatNamazov/SampX/assets/70571714/708965f7-82c1-48fa-99c9-0fe5ef3d8139

**Comment by RinatNamazov** [comment]
Check the new latest version [v1.1.0-beta](https://github.com/RinatNamazov/SampX/releases/tag/v1.1.0-beta).

**Comment by Vladik01-11** [comment]
It seems that this bug has been fixed, but another one has arisen.

You have returned the sorting in this release, it sorts first closed, then all and at the end inaccessible, but this sorting itself is a big mistake.
Here is an example, I have 6 servers, the password-protected servers immediately flew to the top, but there was one left when I deleted the server between the password-protected and active, then my active server became between the servers under a password. After restarting, the active server was back in its place, strangely 🤨.
Please add the sorting option to the settings, because it does not sort as it should and I, as a user, am not comfortable sorting in this form.

And also there was another performance, all the servers that should be pinged, for example through the browser, stopped pinging, can you return the server ping?

https://github.com/RinatNamazov/SampX/assets/70571714/ead264b5-4c79-43ae-84da-b8f0c27a1a14

**Comment by RinatNamazov** [comment]
Sorting is disabled by default, before clicking on any of the headers. But in the old version there was a bug when changing the list of servers caused sorting.

Regarding 'pinging through the browser,' it was initially removed temporarily and later there was uncertainty about its necessity.

Check [v1.2.0-beta](https://github.com/RinatNamazov/SampX/releases/tag/v1.2.0-beta)
(UPD: I'm already aware of the bug that occurs after moving the server but before restarting the application.)
